version: '3'

services:
  app:
    container_name: glowing-waffle
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    build: ./docker/mongodb_rs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: refactor_vli
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    restart: always