version: '3'

services:
  app:
    container_name: backend-app
    build: .
    command: npm run start:dev
    ports:
      - 9000:9000
      - 9229:9229
    volumes:
      - .:/app
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3072M

  mongodb:
    image: mongo:7
    container_name: mongodb
    attach: false # desabilita os logs do container no terminal
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
