version: '3'

services:
  app:
    container_name: backend-app
    build: .
    command: npm run start:dev
    ports:
      - '9000:9000'
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mongodb
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 3072M

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    logging:
      driver: none # disable logging

